apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagepools.openebs.io
spec:
  group: openebs.io
  version: v1
  scope: Cluster
  names:
    plural: storagepools
    singular: storagepool
    kind: StoragePool
    shortNames:
    - sp
