package blockdevice

type BlockDevice struct {
	// UUID is the UUID for this BlockDevice generated by NDM
	// It is an md5 hash generated based on the various parameters
	// of the BlockDevice.
	UUID string

	// NodeAttributes contains the details of the node on which
	// the BlockDevice is attached
	NodeAttributes NodeAttribute

	// Path is dev path of a device
	// eg : /dev/sda, /dev/sda1, /dev/dm-0
	Path string

	// FSInfo contains the file system related information of this
	// BlockDevice if it exists
	FSInfo FileSystemInformation
}

type NodeAttribute map[NodeAttributeKey]string

type NodeAttributeKey string

const (
	HostName   NodeAttributeKey = "hostname"
	NodeName   NodeAttributeKey = "nodename"
	ZoneName   NodeAttributeKey = "zone"
	RegionName NodeAttributeKey = "region"
)

type FileSystemInformation struct {
	FileSystem string
	MountPoint []string
}
