package udev

import (
	"github.com/openebs/node-disk-manager/integration_tests/utils"
	"strings"
)

// UDEV events available in the system
const (
	UdevEventAdd    = "add"
	UdevEventRemove = "remove"
	UdevEventChange = "change"
)

var execCommandWithPipe = utils.ExecCommandWithPipe

// TriggerEvent triggers a udev event for the device with syspath.
// The event is generated by writing the event action into
// syspath/devicename/uevent file. This write will cause UDEV to trigger
// the corresponding event. It is same as using `udevadm trigger`
func TriggerEvent(event, syspath, devicePath string) error {
	splitName := strings.Split(devicePath, "/")
	deviceName := splitName[len(splitName)-1]
	fileName := syspath + "/" + deviceName + "/uevent"
	command1 := "echo " + event
	command2 := "sudo tee " + fileName
	_, err := execCommandWithPipe(command1, command2)
	return err
}
