apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devicerequests.openebs.io
spec:
  group: openebs.io
  names:
    kind: DeviceRequest
    listKind: DeviceRequestList
    plural: devicerequests
    singular: devicerequest
  scope: Cluster
  version: v1alpha1
