apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndm-cluster-exporter
  labels:
    app: openebs
    component: ndm-cluster-exporter
    openebs.io/component-name: ndm-cluster-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openebs
      component: ndm-cluster-exporter
      openebs.io/component-name: ndm-cluster-exporter
  template:
    metadata:
      labels:
        name: ndm-cluster-exporter
        app: openebs
        component: ndm-cluster-exporter
        openebs.io/component-name: ndm-cluster-exporter
      annotations:
        # Annotations added so that prometheus can automatically scrape metrics from the
        # exporter
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9100'
    spec:
      serviceAccountName: openebs-ndm
      containers:
        - name: ndm-cluster-exporter
          image: openebs/node-disk-exporter-amd64:ci
          command:
            - /usr/local/bin/exporter
          args:
            - "start"
            - "--mode=cluster"
            - "--port=:9100"
            - "--metrics=/metrics"
          ports:
            - containerPort: 9100
              protocol: TCP
              name: metrics
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
