apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ndm-operator
  template:
    metadata:
      labels:
        name: ndm-operator
    spec:
      serviceAccountName: ndm-operator
      containers:
        - name: ndm-operator
          # Replace this with the built image name
          image: quay.io/prateek14/ndm-operator
	  imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ndm-operator
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ndm-operator"
